[book]
title = "The Open Source Way"
authors = ["The Open Source Way Community"]
language = "zh-cn"
multilingual = false
src = "content"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/theopensourcewaycn/guidebook-site"
edit-url-template = "https://github.com/theopensourcewaycn/guidebook/edit/main-cn/../{path}"

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = true

# 预处理器：处理 YAML front matter
[preprocessor.frontmatter]
